# Header
menu:
  Home: /
  Artigos: /archives
rss: /atom.xml

# Content
excerpt_link: Leia Mais
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- archive


# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id: